pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                sh 'python3 -m pytest --cov-report term --cov-report xml:coverage.xml --cov=to-do'
            }
            post {
                always {
                    junit 'test-reports/results.xml', skipPublishingChecks: true
                }
            }

        }

    }
}
