pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                sh 'python3 -m pytest'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }

        }

    }
}
